### ISSUE TITLE
Only show urineVolume data when viewing "Two Weeks"

### ISSUE THREAD

**Issue by wcchung** [MyDataTaiwan/mylog14-dashboard#42]
**Steps to Reproduce**

1. Using magic button to generate data for 9 days in MyLog with HF package
2. Update data to LogBoard
3. get link: https://logboard-dev.numbersprotocol.io/logboard-frontend/a4fb9ba8-2a6a-46ba-9947-c46422dfae93
4. Switch to view data in "Two weeks"
5. See only urine Volume data

**Results**

* Expected: Can see all data (urineVolume, SBP, DBP...and so on)
* Actual:  See only urineVolume

**Logs**

![螢幕快照 2020-08-03 下午5 36 27](https://user-images.githubusercontent.com/12252921/89169425-cbe58b00-d5b0-11ea-8c57-47dacc313e48.png)

**Environment**

* mylog14-dashboard: v0.5.0
* MyLog App: v0.11.6

**Comment by wcchung** [comment]
There are data other than urineVolume in 7/25

![image](https://user-images.githubusercontent.com/12252921/89169668-1a932500-d5b1-11ea-910f-601410e6147b.png)

**Comment by wcchung** [comment]
------ Copy from Slack ------
James  17:43
@DaYuan 有可能是因為除了尿量以外剛好兩週的時候其他資料第一筆都是 null
17:43
我猜可能跟這有關

--------------------------

@CS6 @shc261392 
For my record in 7/23 (Day 1), I only record 50ml urineVolume. 
For my record in 7/25 (Day 2), I had all data type.

**Comment by wcchung** [comment]
Also, the urineVolume in pop-up windows is wrong. 
![螢幕快照 2020-08-03 下午5 54 23](https://user-images.githubusercontent.com/12252921/89170595-75794c00-d5b2-11ea-8b5b-86af8d64ec18.png)
![螢幕快照 2020-08-03 下午5 55 46](https://user-images.githubusercontent.com/12252921/89170696-98a3fb80-d5b2-11ea-8e0b-5822122c1170.png)

**Comment by scott-dt** [comment]
v0.12.2 8/9 紀錄一筆只有尿量的資料 (如果第一筆資料有除了尿量以外的資料都可正常顯示)
            8/10 紀錄體重血壓資料一筆
上傳 logboard v0.1.2 https://logboard-dev.numbersprotocol.io/logboard-frontend/222e98b5-8fa6-4841-9ac4-d078a2f2148e
完全無資料顯示
![image](https://user-images.githubusercontent.com/62582260/89751845-6ccdcc00-db04-11ea-8451-0d6a4e62fa0d.png)

**Comment by wcchung** [comment]
@scott-dt 感謝~~ 請好好 keep 這筆資料，之後要靠它才能 verify 這個 issue

**Comment by wcchung** [comment]
![螢幕快照 2020-08-12 下午4 15 44](https://user-images.githubusercontent.com/12252921/89991918-21a7ea80-dcb7-11ea-9e10-18791e2aa638.png)
![螢幕快照 2020-08-12 下午4 15 58](https://user-images.githubusercontent.com/12252921/89991929-240a4480-dcb7-11ea-9a03-c2406c58553a.png)
