### ISSUE TITLE
[FR] User can share & view 自我健康聲明 data on LogBoard

### ISSUE THREAD

**Issue by wcchung** [MyDataTaiwan/mylog14-dashboard#44]
**Concept**
If we provide a dashboard show 自我健康聲明 on dashboard. 

**Reason/Hypothesis**

**More Description (if any)**

Put more description here to support the concept

**Suggested Implementation (if any)**

Put some suggested implementation here if you already have some ideas in mind

**Comment by scott-dt** [comment]
0.1.6 健康聲明表頁面有顯示 ，目前0.12.3 版本 app  還無法記錄健康聲明表 。暫時無法確定顯示是否正常 ，尚未壓 fix verified tag

**Comment by scott-dt** [comment]
![image](https://user-images.githubusercontent.com/62582260/91010222-ac240e80-e614-11ea-9567-b9ad23244d84.png)

**Comment by scott-dt** [comment]
20200824 Second confirmation by scott
