### ISSUE TITLE
calendar 下方 Today 按鍵沒反應

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14-dashboard#47]
**Steps to Reproduce**

1. 點擊 calendar 下方 Today 按鍵
2. 沒有任何反應

**Results**
* Expected: calendar 下方 Today 按鍵數據會跳到今天的資料
* Actual: calendar 下方 Today 按鍵沒反應

**Environment**
* mylog14-dashboard: v0.1.2
* chrome (84.0.4147.105) & Microsoft Edge (84.0.522.52)

**Comment by scott-dt** [comment]
200806 確認功能 於 kickoff 討論將此按鈕取消

**Comment by CS6** [comment]
fixed

**Comment by scott-dt** [comment]
0.1.6  calendar 下方 Today 按鍵已刪除 
![image](https://user-images.githubusercontent.com/62582260/90586857-bc9a4a80-e20a-11ea-9cbe-a5e89be2721c.png)

**Comment by scott-dt** [comment]
20200824 Second confirmation by scott
