### ISSUE TITLE
Need to show symptom title even when there's no symptom

### ISSUE THREAD

**Issue by wcchung** [MyDataTaiwan/mylog14-dashboard#49]
**Steps to Reproduce**

1. Upload records when user haven't record any data for today.
2. Open LogBoard to view the records

**Results**
User can't see any symptom title in right down corner
![螢幕快照 2020-08-17 下午4 53 40](https://user-images.githubusercontent.com/12252921/90379839-d8d4a500-e0ad-11ea-8ef5-a5b81d358676.png)

* Expected:
User should see symptom title in right down corner even there's no records for symptoms
![螢幕快照 2020-08-17 下午5 24 11](https://user-images.githubusercontent.com/12252921/90380307-7cbe5080-e0ae-11ea-8a63-dd583b89731b.png)

* Actual: 
User can't see any symptom title in right down corner

**Logs**

* <upload-error-log-here>

**Environment**

* mylog14-dashboard: v0.5.2-beta5

**Comment by wcchung** [comment]
[Copy Form Slack]
```
DaYuan 21:26
49應該不行，雖然是小細節但改動的影響不小，其他的應該可以
21:29
應該說是能暫時修掉（寫死），只是之後要配合模板又要重做

tammy  21:34
@sherry 49 有一定需要嗎?

sherry  21:36
@Tammy #49 目前沒有影響 Function。可以先不修或是 workaround 處理。 
```

According to discussion on 2020/8/17, move this issue to Backlog

**Comment by shc261392** [comment]
@CS6 

Getting data template:

`GET: {{hostUrl}}/api/v1/records/templates/?template=commonCold`
`GET: {{hostUrl}}/api/v1/records/templates/?template=heartFailure`
`GET: {{hostUrl}}/api/v1/records/templates/?template=healthDeclaration`

Here's an example response for the commonCold:

```
{
    "templateName": "commonCold",
    "keyFieldName": "bodyTemperature",
    "dataGroups": [
        "vitalSigns",
        "symptoms",
        "additionalInformation"
    ],
    "fields": [
        {
            "name": "bodyTemperature",
            "icon": "thermometer-outline",
            "type": "number",
            "dataGroup": "vitalSigns",
            "dataClass": "highest",
            "valueRange": {
                "max": 41,
                "min": 34
            },
            "valueUnit": "°C"
        },
        {
            "name": "coughing",
            "icon": "medkit-outline",
            "type": "boolean",
            "dataGroup": "symptoms",
            "dataClass": "toggle"
        },
        {
            "name": "runnyNose",
            "icon": "medkit-outline",
            "type": "boolean",
            "dataGroup": "symptoms",
            "dataClass": "toggle"
        },
        {
            "name": "nasalCongestion",
            "icon": "medkit-outline",
            "type": "boolean",
            "dataGroup": "symptoms",
            "dataClass": "toggle"
        },
        {
            "name": "sneezing",
            "icon": "medkit-outline",
            "type": "boolean",
            "dataGroup": "symptoms",
            "dataClass": "toggle"
        },
        {
            "name": "note",
            "icon": "pencil-outline",
            "type": "string",
            "dataGroup": "additionalInformation",
            "dataClass": "note"
        },
        {
            "name": "photo",
            "icon": "camera-outline",
            "type": "photo",
            "dataGroup": "additionalInformation",
            "dataClass": "photo"
        }
    ]
}
```

To identify a field which is the `symptoms` type, check the `dataGroup` field
(It is a symptom if `dataGroup` has `symptoms` as value

因為 API 還是需要花一些時間得到回應，建議在網站載入後先取全部紀錄模式的資料存下來，不要點開該紀錄模式才做這個 API request

**Comment by scott-dt** [comment]
![image](https://user-images.githubusercontent.com/62582260/92209493-aacdce00-eebf-11ea-966f-218658227532.png)

**Comment by scott-dt** [comment]
200904 verified by scott
