### ISSUE TITLE
User should see the same layout with "Today" when they select specific date

### ISSUE THREAD

**Issue by wcchung** [MyDataTaiwan/mylog14-dashboard#50]
**Steps to Reproduce**

1. User upload record to LogBoard (with Today's data)
test data: https://logboard-qa.numbersprotocol.io/d9034e81-e31c-4454-a390-a117657760bc

**Results**
When user select "Today" (date: 2020/8/17), they see
![螢幕快照 2020-08-17 下午4 54 53](https://user-images.githubusercontent.com/12252921/90381140-885e4700-e0af-11ea-9539-f1cd68f68836.png)

Then user select to specific date (date: 2020/8/17) in calendar, they see
![螢幕快照 2020-08-17 下午4 59 28](https://user-images.githubusercontent.com/12252921/90381254-adeb5080-e0af-11ea-9ac5-6d2e3cdfd255.png)

* Expected:
User should see the same layout for specific date (2020/8/17) as they view the data "Today"

* Actual: 
User see different layout for the exactly the same record but different manipulation.

**Logs**

* <upload-error-log-here>

**Environment**

* mylog14-dashboard: v0.5.2-beta5

**Comment by CS6** [comment]
原因：
目前的API主要有2組
` api/v1/records/summary/?uid=UUID&template=heartFailure&start_date=2020-07-15&end_date=2020-07-24`;`

`api/v1/records/past-days/?uid=UUID&template=heartFailure&range=this-month`

當是期選擇器 選取單日時
` api/v1/records/summary/?uid=UUID&template=heartFailure&start_date=2020-08-18&end_date=2020-08-18`;`
只會取道當日單筆資料
需要改用
`api/v1/records/past-days/?uid=UUID&template=heartFailure&range=today`
但是當日期不為當日就無法了 （目前的解法，我看了超久才發現ＱＱ，一直以為是bug）

可能需要將條件改為 `日期` (CC @shc261392 )
`api/v1/records/past-days/?uid=UUID&template=heartFailure&range=2020-08-18`

**Comment by scott-dt** [comment]
v0.1.6
1. 用左上方日期區間點選 (2020/08/17) 非當日 
2. 無法顯示點選 (2020/08/17) 的紀錄 ，而是顯示當日(2020/08/19)的紀錄
![image](https://user-images.githubusercontent.com/62582260/90587177-4e09bc80-e20b-11ea-84fa-084c548b8431.png)

**Comment by wcchung** [comment]
根據 Slack channel 上的討論，此 milestone 先不處理此 issue，移到 backlog

**Comment by shc261392** [comment]
@CS6 

The `/api/v1/records/summary` API endpoint will return complete data of the day if `start_date` equals `end_date`.

Example: `{{hostUrl}}/api/v1/records/summary?uid=33d30286-08d8-4744-9ab0-e4e2042e25fe&template=commonCold&start_date=2020-08-28&end_date=2020-08-28`

**Comment by scott-dt** [comment]
![image](https://user-images.githubusercontent.com/62582260/92208889-ace35d00-eebe-11ea-886e-d54980cbbc2c.png)
![image](https://user-images.githubusercontent.com/62582260/92208914-b5d42e80-eebe-11ea-968c-a923390c87a5.png)

**Comment by scott-dt** [comment]
200904 verified by scott
