### ISSUE TITLE
When user switch data window by "Today", "This Week" .. buttons, the calendar on top should also sync

### ISSUE THREAD

**Issue by wcchung** [MyDataTaiwan/mylog14-dashboard#51]
**Steps to Reproduce**

1. User upload data to LogBoard
2. User switch the data window by the buttons "Today", "This Week"...... etc.

**Results**
![image](https://user-images.githubusercontent.com/12252921/90381993-c27c1880-e0b0-11ea-899f-104e26c24507.png)
![image (1)](https://user-images.githubusercontent.com/12252921/90382000-c4de7280-e0b0-11ea-800a-a3d65a0185f6.png)
![image (2)](https://user-images.githubusercontent.com/12252921/90382002-c5770900-e0b0-11ea-9efd-c939c3f1a313.png)
![image (3)](https://user-images.githubusercontent.com/12252921/90382004-c6a83600-e0b0-11ea-8201-50deb55879ad.png)

* Expected:
   When user switch data windows, the date in the top calendar should also sync with the data window

* Actual: 
   The date in the top calendar won't alter when switching data window by buttons

**Logs**

* <upload-error-log-here>

**Environment**

* mylog14-dashboard: v0.5.2-beta5

**Comment by scott-dt** [comment]
1. 點選上方日期區間選項 (2020/08/04~2020/08/07)
2. 圖表顯示日期區間為 ( 2020/08/04~2020/08/06 ) 並不相符選取日期區間
![image](https://user-images.githubusercontent.com/62582260/90587970-1ef44a80-e20d-11ea-8906-ad62a1aadd4c.png)

**Comment by scott-dt** [comment]
20200824 Second confirmation by scott
![image](https://user-images.githubusercontent.com/62582260/91033156-822f1400-e635-11ea-9c50-e340e46dc896.png)
