### ISSUE TITLE
Remove pop-up window when user click data icon

### ISSUE THREAD

**Issue by wcchung** [MyDataTaiwan/mylog14-dashboard#52]
**Steps to Reproduce**

1. User upload data to LogBoard
2. User select a specific data icon on LogBoard

**Results**
The position of pop-up window is weird, and the content is not readable. User have no idea what the pop-up windows for.

![螢幕快照 2020-08-17 下午4 51 37](https://user-images.githubusercontent.com/12252921/90382839-dffdb200-e0b1-11ea-8a9c-7a8c0c482562.png)
![螢幕快照 2020-08-17 下午4 51 55](https://user-images.githubusercontent.com/12252921/90382843-e1c77580-e0b1-11ea-897d-2baf2a640bd3.png)

* Expected:
If #50 is fixed, then the pop-up windows is no need for now.

* Actual: 
See results

**Logs**

* <upload-error-log-here>

**Environment**

* mylog14-dashboard: v0.5.2-beta5

**Comment by scott-dt** [comment]
v0.1.6  
pop-up windows 已刪除 ，點選後並未顯示 。 但#50 並未修正

**Comment by scott-dt** [comment]
20200824 Second confirmation by scott
