### ISSUE TITLE
[UI Update] The summary image in LogBoard is not consistent with summary image in MyLog

### ISSUE THREAD

**Issue by wcchung** [MyDataTaiwan/mylog14-dashboard#57]
**Update Purpose**
[WIP]
**UI Suggestion**

Put images or link to the contents of suggestions

**More Description (if any)**

Put more description here to help developers understand

**Comment by shc261392** [comment]
@CS6 

The `/api/v1/records/summary` API endpoint will return complete data of the day if `start_date` equals `end_date`.

Example: `{{hostUrl}}/api/v1/records/summary?uid=33d30286-08d8-4744-9ab0-e4e2042e25fe&template=commonCold&start_date=2020-08-28&end_date=2020-08-28`

**Comment by scott-dt** [comment]
會顯示當天最新的照片
